# Needed for PHP 5.6 + 7.0 support
dist: xenial

# Project language
language: php

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  include:
    - php: 7.3

# Define an environment variable
env:
  - SYMFONY_VERSION="3.4.*"

# Update composer
before-install:
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install

# Run script
script:
  - vendor/bin/phpunit
