imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
        name: MOCKSESSION
    profiler:
        collect: false
    validation: { enable_annotations: true }

web_profiler:
    toolbar: false
    intercept_redirects: false

liip_test_fixtures:
    cache_db:
        sqlite: liip_test_fixtures.services_database_backup.sqlite

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_sqlite
                path: %kernel.cache_dir%/test.db
