services:
    mautic_stats.stats.model:
        class: Mautic\StatsBundle\Model\StatsModel
        arguments: ["@doctrine.orm.default_entity_manager"]

    mautic_stats.mautic3upgrade.model:
        class: Mautic\StatsBundle\Model\Mautic3UpgradeStatsModel
        arguments: ["@doctrine.orm.default_entity_manager"]

    mautic_stats.twig_extension:
        class: Mautic\StatsBundle\Twig\StatsExtension
        public: false
        tags:
            - { name: twig.extension }

    Mautic\StatsBundle\DataFixtures\ORM\:
        resource: '../../DataFixtures/ORM/*'
        tags: ['doctrine.fixture.orm']
